plugins {
    id 'idea'
    id 'fabric-loom' version '1.10-SNAPSHOT' apply false
    id 'com.replaymod.preprocess' version '9d21b334a7'
    id 'me.fallenbreath.yamlang' version '1.4.1' apply false
}

preprocess {
    strictExtraMappings = false
    def mc12104 = createNode('1.21.4', 1_21_04, '')
}

tasks.register('buildAndGather') {
    subprojects {
        dependsOn project.tasks.named('build').get()
    }
    doFirst {
        println 'Gathering builds'
        def buildLibs = { p -> p.buildDir.toPath().resolve('libs') }
        delete fileTree(buildLibs(rootProject)) {
            include '*'
        }
        subprojects {
            copy {
                from(buildLibs(project)) {
                    include '*.jar'
                    exclude '*-dev.jar', '*-sources.jar'
                }
                into buildLibs(rootProject).resolve('v' + project.mod_version)
                duplicatesStrategy DuplicatesStrategy.INCLUDE
            }
            delete(buildLibs(project))
        }
    }
}

idea {
    module {
        excludeDirs += [
                file('src'),
                file('build'),
                file('.gradle'),
                file('run')
        ]
    }
}
